
services:
  mysql:
    image: mysql:8.0.27  #  mysql 镜像版本
    restart: always
    container_name: mysql  # 构建的容器名称
    command:
      --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    #数据卷 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/var/lib/mysql:/var/lib/mysql  #默认呢挂载目录为当前目录
      - $PWD/mysqlBackup:/data/mysqlBackup
    environment:
      # 自定义root密码修改此处
      MYSQL_ROOT_PASSWORD: <your password>
      MYSQL_ROOT_HOST: '%' #root 用户允许从哪个主机连接, % 表示所有